apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2  # Burada 2 pod (konteyner) paralel qalxacaq
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: my-python-image:latest
        ports:
        - containerPort: 5000
